// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eWeather.Backend.Models;

#nullable disable

namespace eWeather.Backend.Migrations
{
    [DbContext(typeof(EWeatherContext))]
    partial class EWeatherContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("eWeather.Backend.Models.WeerMeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("FeelTemperature")
                        .HasColumnType("REAL");

                    b.Property<float>("GroundTemperature")
                        .HasColumnType("REAL");

                    b.Property<float>("RainFallLastHour")
                        .HasColumnType("REAL");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("SunPower")
                        .HasColumnType("REAL");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Tijdstip")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindDirection")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeerMetingen");
                });
#pragma warning restore 612, 618
        }
    }
}
